jobs: 350
cluster: "sbatch -p interactive -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o logs_slurm/{rule}_{wildcards} -e logs_slurm/{rule}_{wildcards} --mail-type=FAIL --mail-user=vshanka@clemson.edu"
resources: [cpus=366, mem_mb=1000000]
